CREATE TABLE refresh_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    token      VARCHAR(2048)                           NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name                 VARCHAR(255)                            NOT NULL,
    phone_number              VARCHAR(255)                            NOT NULL,
    email                     VARCHAR(255)                            NOT NULL,
    password_hash             VARCHAR(255),
    role                      VARCHAR(255),
    reset_password_token      VARCHAR(255),
    reset_password_expires_at TIMESTAMP WITHOUT TIME ZONE,
    created_at                TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_token UNIQUE (token);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phonenumber UNIQUE (phone_number);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT FK_REFRESH_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);